### ISSUE TITLE
Traceback when trying to access a view by clicking an image file

### ISSUE THREAD

**Issue by foxbunny** [Outernet-Project/librarian-content#15]
```
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/databases/plugins.py", line 11, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/sessions/plugins.py", line 37, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_core/contrib/auth/plugins.py", line 32, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/bottle_utils/i18n.py", line 387, in wrapper
    return callback(*args, **kwargs)
  File "/usr/bin/bottle.py", line 1729, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python2.7/site-packages/librarian_setup/plugins.py", line 25, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_captive/plugins.py", line 26, in wrapper
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_filemanager/routes.py", line 286, in init_file_action
    return show_view(path, view, defaults)
  File "/usr/lib/python2.7/site-packages/librarian_filemanager/routes.py", line 164, in show_view
    return show_list_view(path, view, defaults)
  File "/usr/lib/python2.7/site-packages/bottle_utils/ajax.py", line 68, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_filemanager/routes.py", line 129, in show_list_view
    for f, facets in izip_longest(files, facets_list):
  File "/usr/lib/python2.7/site-packages/librarian_content/facets/utils.py", line 46, in get_facets
    facets = archive.get_facets(path, facet_type=facet_type)
  File "/usr/lib/python2.7/site-packages/librarian_content/facets/archive.py", line 127, in get_facets
    data = self.one(q, (parent, name))
  File "/usr/lib/python2.7/site-packages/librarian_content/facets/archive.py", line 36, in wrapper
    row = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/librarian_content/facets/archive.py", line 118, in one
    return self.db.fetchone(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/squery_pg/squery_pg.py", line 79, in wrapper
    return func(self, query, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/squery_pg/squery_pg.py", line 95, in fetchone
    return self.pool.fetchone(query, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/squery_pg/pool.py", line 129, in fetchone
    cursor.execute(*args)
  File "/usr/lib/python2.7/site-packages/psycopg2/extras.py", line 120, in execute
    return super(DictCursor, self).execute(query, vars)
ProgrammingError: column "file" does not exist
LINE 1: ...s WHERE path = 'Community Uploads/2016_02_14' and file ='201...
                                                             ^
```

**Comment by foxbunny** [comment]
Just an issue migation from an alpha version. Closing.
